
name: Compile Sming example

on: [push, pull_request]
jobs:
  Basic_Blink:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@master
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y make unrar autoconf automake libtool libtool-bin gcc g++ gperf \
          flex bison texinfo gawk ncurses-dev libexpat1-dev python sed python-serial \
          python-dev srecord bc git help2man unzip bzip2
    - name: Compile
      run: |
        pwd
        ls -al $GITHUB_WORKSPACE
        python --version
        git clone -b master https://github.com/SmingHub/Sming.git
